// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package handler

//go:generate minimock -i github.com/gegeog/go-mentor-junior/services/restaurant/internal/api/handler.RestaurantService -o restaurant_service_mock_test.go -n RestaurantServiceMock -p handler

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"
	"uuid"

	"github.com/gegeog/go-mentor-junior/services/restaurant/internal/domain"
	"github.com/gojuno/minimock/v3"
)

// RestaurantServiceMock implements RestaurantService
type RestaurantServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetItem          func(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID) (m1 domain.MenuItem, err error)
	funcGetItemOrigin    string
	inspectFuncGetItem   func(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID)
	afterGetItemCounter  uint64
	beforeGetItemCounter uint64
	GetItemMock          mRestaurantServiceMockGetItem

	funcGetItems          func(ctx context.Context, u1 uuid.UUID) (ma1 []domain.MenuItem, err error)
	funcGetItemsOrigin    string
	inspectFuncGetItems   func(ctx context.Context, u1 uuid.UUID)
	afterGetItemsCounter  uint64
	beforeGetItemsCounter uint64
	GetItemsMock          mRestaurantServiceMockGetItems

	funcGetRestaurant          func(ctx context.Context, u1 uuid.UUID) (r1 domain.Restaurant, err error)
	funcGetRestaurantOrigin    string
	inspectFuncGetRestaurant   func(ctx context.Context, u1 uuid.UUID)
	afterGetRestaurantCounter  uint64
	beforeGetRestaurantCounter uint64
	GetRestaurantMock          mRestaurantServiceMockGetRestaurant

	funcGetRestaurants          func(ctx context.Context) (ra1 []domain.Restaurant, err error)
	funcGetRestaurantsOrigin    string
	inspectFuncGetRestaurants   func(ctx context.Context)
	afterGetRestaurantsCounter  uint64
	beforeGetRestaurantsCounter uint64
	GetRestaurantsMock          mRestaurantServiceMockGetRestaurants

	funcPutMenuItem          func(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem) (m2 domain.MenuItem, err error)
	funcPutMenuItemOrigin    string
	inspectFuncPutMenuItem   func(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem)
	afterPutMenuItemCounter  uint64
	beforePutMenuItemCounter uint64
	PutMenuItemMock          mRestaurantServiceMockPutMenuItem

	funcPutRestaurant          func(ctx context.Context, r1 domain.Restaurant) (r2 domain.Restaurant, err error)
	funcPutRestaurantOrigin    string
	inspectFuncPutRestaurant   func(ctx context.Context, r1 domain.Restaurant)
	afterPutRestaurantCounter  uint64
	beforePutRestaurantCounter uint64
	PutRestaurantMock          mRestaurantServiceMockPutRestaurant
}

// NewRestaurantServiceMock returns a mock for RestaurantService
func NewRestaurantServiceMock(t minimock.Tester) *RestaurantServiceMock {
	m := &RestaurantServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetItemMock = mRestaurantServiceMockGetItem{mock: m}
	m.GetItemMock.callArgs = []*RestaurantServiceMockGetItemParams{}

	m.GetItemsMock = mRestaurantServiceMockGetItems{mock: m}
	m.GetItemsMock.callArgs = []*RestaurantServiceMockGetItemsParams{}

	m.GetRestaurantMock = mRestaurantServiceMockGetRestaurant{mock: m}
	m.GetRestaurantMock.callArgs = []*RestaurantServiceMockGetRestaurantParams{}

	m.GetRestaurantsMock = mRestaurantServiceMockGetRestaurants{mock: m}
	m.GetRestaurantsMock.callArgs = []*RestaurantServiceMockGetRestaurantsParams{}

	m.PutMenuItemMock = mRestaurantServiceMockPutMenuItem{mock: m}
	m.PutMenuItemMock.callArgs = []*RestaurantServiceMockPutMenuItemParams{}

	m.PutRestaurantMock = mRestaurantServiceMockPutRestaurant{mock: m}
	m.PutRestaurantMock.callArgs = []*RestaurantServiceMockPutRestaurantParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRestaurantServiceMockGetItem struct {
	optional           bool
	mock               *RestaurantServiceMock
	defaultExpectation *RestaurantServiceMockGetItemExpectation
	expectations       []*RestaurantServiceMockGetItemExpectation

	callArgs []*RestaurantServiceMockGetItemParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RestaurantServiceMockGetItemExpectation specifies expectation struct of the RestaurantService.GetItem
type RestaurantServiceMockGetItemExpectation struct {
	mock               *RestaurantServiceMock
	params             *RestaurantServiceMockGetItemParams
	paramPtrs          *RestaurantServiceMockGetItemParamPtrs
	expectationOrigins RestaurantServiceMockGetItemExpectationOrigins
	results            *RestaurantServiceMockGetItemResults
	returnOrigin       string
	Counter            uint64
}

// RestaurantServiceMockGetItemParams contains parameters of the RestaurantService.GetItem
type RestaurantServiceMockGetItemParams struct {
	ctx context.Context
	u1  uuid.UUID
	u2  uuid.UUID
}

// RestaurantServiceMockGetItemParamPtrs contains pointers to parameters of the RestaurantService.GetItem
type RestaurantServiceMockGetItemParamPtrs struct {
	ctx *context.Context
	u1  *uuid.UUID
	u2  *uuid.UUID
}

// RestaurantServiceMockGetItemResults contains results of the RestaurantService.GetItem
type RestaurantServiceMockGetItemResults struct {
	m1  domain.MenuItem
	err error
}

// RestaurantServiceMockGetItemOrigins contains origins of expectations of the RestaurantService.GetItem
type RestaurantServiceMockGetItemExpectationOrigins struct {
	origin    string
	originCtx string
	originU1  string
	originU2  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetItem *mRestaurantServiceMockGetItem) Optional() *mRestaurantServiceMockGetItem {
	mmGetItem.optional = true
	return mmGetItem
}

// Expect sets up expected params for RestaurantService.GetItem
func (mmGetItem *mRestaurantServiceMockGetItem) Expect(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID) *mRestaurantServiceMockGetItem {
	if mmGetItem.mock.funcGetItem != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Set")
	}

	if mmGetItem.defaultExpectation == nil {
		mmGetItem.defaultExpectation = &RestaurantServiceMockGetItemExpectation{}
	}

	if mmGetItem.defaultExpectation.paramPtrs != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by ExpectParams functions")
	}

	mmGetItem.defaultExpectation.params = &RestaurantServiceMockGetItemParams{ctx, u1, u2}
	mmGetItem.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetItem.expectations {
		if minimock.Equal(e.params, mmGetItem.defaultExpectation.params) {
			mmGetItem.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetItem.defaultExpectation.params)
		}
	}

	return mmGetItem
}

// ExpectCtxParam1 sets up expected param ctx for RestaurantService.GetItem
func (mmGetItem *mRestaurantServiceMockGetItem) ExpectCtxParam1(ctx context.Context) *mRestaurantServiceMockGetItem {
	if mmGetItem.mock.funcGetItem != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Set")
	}

	if mmGetItem.defaultExpectation == nil {
		mmGetItem.defaultExpectation = &RestaurantServiceMockGetItemExpectation{}
	}

	if mmGetItem.defaultExpectation.params != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Expect")
	}

	if mmGetItem.defaultExpectation.paramPtrs == nil {
		mmGetItem.defaultExpectation.paramPtrs = &RestaurantServiceMockGetItemParamPtrs{}
	}
	mmGetItem.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetItem.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetItem
}

// ExpectU1Param2 sets up expected param u1 for RestaurantService.GetItem
func (mmGetItem *mRestaurantServiceMockGetItem) ExpectU1Param2(u1 uuid.UUID) *mRestaurantServiceMockGetItem {
	if mmGetItem.mock.funcGetItem != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Set")
	}

	if mmGetItem.defaultExpectation == nil {
		mmGetItem.defaultExpectation = &RestaurantServiceMockGetItemExpectation{}
	}

	if mmGetItem.defaultExpectation.params != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Expect")
	}

	if mmGetItem.defaultExpectation.paramPtrs == nil {
		mmGetItem.defaultExpectation.paramPtrs = &RestaurantServiceMockGetItemParamPtrs{}
	}
	mmGetItem.defaultExpectation.paramPtrs.u1 = &u1
	mmGetItem.defaultExpectation.expectationOrigins.originU1 = minimock.CallerInfo(1)

	return mmGetItem
}

// ExpectU2Param3 sets up expected param u2 for RestaurantService.GetItem
func (mmGetItem *mRestaurantServiceMockGetItem) ExpectU2Param3(u2 uuid.UUID) *mRestaurantServiceMockGetItem {
	if mmGetItem.mock.funcGetItem != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Set")
	}

	if mmGetItem.defaultExpectation == nil {
		mmGetItem.defaultExpectation = &RestaurantServiceMockGetItemExpectation{}
	}

	if mmGetItem.defaultExpectation.params != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Expect")
	}

	if mmGetItem.defaultExpectation.paramPtrs == nil {
		mmGetItem.defaultExpectation.paramPtrs = &RestaurantServiceMockGetItemParamPtrs{}
	}
	mmGetItem.defaultExpectation.paramPtrs.u2 = &u2
	mmGetItem.defaultExpectation.expectationOrigins.originU2 = minimock.CallerInfo(1)

	return mmGetItem
}

// Inspect accepts an inspector function that has same arguments as the RestaurantService.GetItem
func (mmGetItem *mRestaurantServiceMockGetItem) Inspect(f func(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID)) *mRestaurantServiceMockGetItem {
	if mmGetItem.mock.inspectFuncGetItem != nil {
		mmGetItem.mock.t.Fatalf("Inspect function is already set for RestaurantServiceMock.GetItem")
	}

	mmGetItem.mock.inspectFuncGetItem = f

	return mmGetItem
}

// Return sets up results that will be returned by RestaurantService.GetItem
func (mmGetItem *mRestaurantServiceMockGetItem) Return(m1 domain.MenuItem, err error) *RestaurantServiceMock {
	if mmGetItem.mock.funcGetItem != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Set")
	}

	if mmGetItem.defaultExpectation == nil {
		mmGetItem.defaultExpectation = &RestaurantServiceMockGetItemExpectation{mock: mmGetItem.mock}
	}
	mmGetItem.defaultExpectation.results = &RestaurantServiceMockGetItemResults{m1, err}
	mmGetItem.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetItem.mock
}

// Set uses given function f to mock the RestaurantService.GetItem method
func (mmGetItem *mRestaurantServiceMockGetItem) Set(f func(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID) (m1 domain.MenuItem, err error)) *RestaurantServiceMock {
	if mmGetItem.defaultExpectation != nil {
		mmGetItem.mock.t.Fatalf("Default expectation is already set for the RestaurantService.GetItem method")
	}

	if len(mmGetItem.expectations) > 0 {
		mmGetItem.mock.t.Fatalf("Some expectations are already set for the RestaurantService.GetItem method")
	}

	mmGetItem.mock.funcGetItem = f
	mmGetItem.mock.funcGetItemOrigin = minimock.CallerInfo(1)
	return mmGetItem.mock
}

// When sets expectation for the RestaurantService.GetItem which will trigger the result defined by the following
// Then helper
func (mmGetItem *mRestaurantServiceMockGetItem) When(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID) *RestaurantServiceMockGetItemExpectation {
	if mmGetItem.mock.funcGetItem != nil {
		mmGetItem.mock.t.Fatalf("RestaurantServiceMock.GetItem mock is already set by Set")
	}

	expectation := &RestaurantServiceMockGetItemExpectation{
		mock:               mmGetItem.mock,
		params:             &RestaurantServiceMockGetItemParams{ctx, u1, u2},
		expectationOrigins: RestaurantServiceMockGetItemExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetItem.expectations = append(mmGetItem.expectations, expectation)
	return expectation
}

// Then sets up RestaurantService.GetItem return parameters for the expectation previously defined by the When method
func (e *RestaurantServiceMockGetItemExpectation) Then(m1 domain.MenuItem, err error) *RestaurantServiceMock {
	e.results = &RestaurantServiceMockGetItemResults{m1, err}
	return e.mock
}

// Times sets number of times RestaurantService.GetItem should be invoked
func (mmGetItem *mRestaurantServiceMockGetItem) Times(n uint64) *mRestaurantServiceMockGetItem {
	if n == 0 {
		mmGetItem.mock.t.Fatalf("Times of RestaurantServiceMock.GetItem mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetItem.expectedInvocations, n)
	mmGetItem.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetItem
}

func (mmGetItem *mRestaurantServiceMockGetItem) invocationsDone() bool {
	if len(mmGetItem.expectations) == 0 && mmGetItem.defaultExpectation == nil && mmGetItem.mock.funcGetItem == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetItem.mock.afterGetItemCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetItem.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetItem implements RestaurantService
func (mmGetItem *RestaurantServiceMock) GetItem(ctx context.Context, u1 uuid.UUID, u2 uuid.UUID) (m1 domain.MenuItem, err error) {
	mm_atomic.AddUint64(&mmGetItem.beforeGetItemCounter, 1)
	defer mm_atomic.AddUint64(&mmGetItem.afterGetItemCounter, 1)

	mmGetItem.t.Helper()

	if mmGetItem.inspectFuncGetItem != nil {
		mmGetItem.inspectFuncGetItem(ctx, u1, u2)
	}

	mm_params := RestaurantServiceMockGetItemParams{ctx, u1, u2}

	// Record call args
	mmGetItem.GetItemMock.mutex.Lock()
	mmGetItem.GetItemMock.callArgs = append(mmGetItem.GetItemMock.callArgs, &mm_params)
	mmGetItem.GetItemMock.mutex.Unlock()

	for _, e := range mmGetItem.GetItemMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m1, e.results.err
		}
	}

	if mmGetItem.GetItemMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetItem.GetItemMock.defaultExpectation.Counter, 1)
		mm_want := mmGetItem.GetItemMock.defaultExpectation.params
		mm_want_ptrs := mmGetItem.GetItemMock.defaultExpectation.paramPtrs

		mm_got := RestaurantServiceMockGetItemParams{ctx, u1, u2}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetItem.t.Errorf("RestaurantServiceMock.GetItem got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItem.GetItemMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.u1 != nil && !minimock.Equal(*mm_want_ptrs.u1, mm_got.u1) {
				mmGetItem.t.Errorf("RestaurantServiceMock.GetItem got unexpected parameter u1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItem.GetItemMock.defaultExpectation.expectationOrigins.originU1, *mm_want_ptrs.u1, mm_got.u1, minimock.Diff(*mm_want_ptrs.u1, mm_got.u1))
			}

			if mm_want_ptrs.u2 != nil && !minimock.Equal(*mm_want_ptrs.u2, mm_got.u2) {
				mmGetItem.t.Errorf("RestaurantServiceMock.GetItem got unexpected parameter u2, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItem.GetItemMock.defaultExpectation.expectationOrigins.originU2, *mm_want_ptrs.u2, mm_got.u2, minimock.Diff(*mm_want_ptrs.u2, mm_got.u2))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetItem.t.Errorf("RestaurantServiceMock.GetItem got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetItem.GetItemMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetItem.GetItemMock.defaultExpectation.results
		if mm_results == nil {
			mmGetItem.t.Fatal("No results are set for the RestaurantServiceMock.GetItem")
		}
		return (*mm_results).m1, (*mm_results).err
	}
	if mmGetItem.funcGetItem != nil {
		return mmGetItem.funcGetItem(ctx, u1, u2)
	}
	mmGetItem.t.Fatalf("Unexpected call to RestaurantServiceMock.GetItem. %v %v %v", ctx, u1, u2)
	return
}

// GetItemAfterCounter returns a count of finished RestaurantServiceMock.GetItem invocations
func (mmGetItem *RestaurantServiceMock) GetItemAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItem.afterGetItemCounter)
}

// GetItemBeforeCounter returns a count of RestaurantServiceMock.GetItem invocations
func (mmGetItem *RestaurantServiceMock) GetItemBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItem.beforeGetItemCounter)
}

// Calls returns a list of arguments used in each call to RestaurantServiceMock.GetItem.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetItem *mRestaurantServiceMockGetItem) Calls() []*RestaurantServiceMockGetItemParams {
	mmGetItem.mutex.RLock()

	argCopy := make([]*RestaurantServiceMockGetItemParams, len(mmGetItem.callArgs))
	copy(argCopy, mmGetItem.callArgs)

	mmGetItem.mutex.RUnlock()

	return argCopy
}

// MinimockGetItemDone returns true if the count of the GetItem invocations corresponds
// the number of defined expectations
func (m *RestaurantServiceMock) MinimockGetItemDone() bool {
	if m.GetItemMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetItemMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetItemMock.invocationsDone()
}

// MinimockGetItemInspect logs each unmet expectation
func (m *RestaurantServiceMock) MinimockGetItemInspect() {
	for _, e := range m.GetItemMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetItem at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetItemCounter := mm_atomic.LoadUint64(&m.afterGetItemCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetItemMock.defaultExpectation != nil && afterGetItemCounter < 1 {
		if m.GetItemMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetItem at\n%s", m.GetItemMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetItem at\n%s with params: %#v", m.GetItemMock.defaultExpectation.expectationOrigins.origin, *m.GetItemMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetItem != nil && afterGetItemCounter < 1 {
		m.t.Errorf("Expected call to RestaurantServiceMock.GetItem at\n%s", m.funcGetItemOrigin)
	}

	if !m.GetItemMock.invocationsDone() && afterGetItemCounter > 0 {
		m.t.Errorf("Expected %d calls to RestaurantServiceMock.GetItem at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetItemMock.expectedInvocations), m.GetItemMock.expectedInvocationsOrigin, afterGetItemCounter)
	}
}

type mRestaurantServiceMockGetItems struct {
	optional           bool
	mock               *RestaurantServiceMock
	defaultExpectation *RestaurantServiceMockGetItemsExpectation
	expectations       []*RestaurantServiceMockGetItemsExpectation

	callArgs []*RestaurantServiceMockGetItemsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RestaurantServiceMockGetItemsExpectation specifies expectation struct of the RestaurantService.GetItems
type RestaurantServiceMockGetItemsExpectation struct {
	mock               *RestaurantServiceMock
	params             *RestaurantServiceMockGetItemsParams
	paramPtrs          *RestaurantServiceMockGetItemsParamPtrs
	expectationOrigins RestaurantServiceMockGetItemsExpectationOrigins
	results            *RestaurantServiceMockGetItemsResults
	returnOrigin       string
	Counter            uint64
}

// RestaurantServiceMockGetItemsParams contains parameters of the RestaurantService.GetItems
type RestaurantServiceMockGetItemsParams struct {
	ctx context.Context
	u1  uuid.UUID
}

// RestaurantServiceMockGetItemsParamPtrs contains pointers to parameters of the RestaurantService.GetItems
type RestaurantServiceMockGetItemsParamPtrs struct {
	ctx *context.Context
	u1  *uuid.UUID
}

// RestaurantServiceMockGetItemsResults contains results of the RestaurantService.GetItems
type RestaurantServiceMockGetItemsResults struct {
	ma1 []domain.MenuItem
	err error
}

// RestaurantServiceMockGetItemsOrigins contains origins of expectations of the RestaurantService.GetItems
type RestaurantServiceMockGetItemsExpectationOrigins struct {
	origin    string
	originCtx string
	originU1  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetItems *mRestaurantServiceMockGetItems) Optional() *mRestaurantServiceMockGetItems {
	mmGetItems.optional = true
	return mmGetItems
}

// Expect sets up expected params for RestaurantService.GetItems
func (mmGetItems *mRestaurantServiceMockGetItems) Expect(ctx context.Context, u1 uuid.UUID) *mRestaurantServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &RestaurantServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.paramPtrs != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by ExpectParams functions")
	}

	mmGetItems.defaultExpectation.params = &RestaurantServiceMockGetItemsParams{ctx, u1}
	mmGetItems.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetItems.expectations {
		if minimock.Equal(e.params, mmGetItems.defaultExpectation.params) {
			mmGetItems.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetItems.defaultExpectation.params)
		}
	}

	return mmGetItems
}

// ExpectCtxParam1 sets up expected param ctx for RestaurantService.GetItems
func (mmGetItems *mRestaurantServiceMockGetItems) ExpectCtxParam1(ctx context.Context) *mRestaurantServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &RestaurantServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.params != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Expect")
	}

	if mmGetItems.defaultExpectation.paramPtrs == nil {
		mmGetItems.defaultExpectation.paramPtrs = &RestaurantServiceMockGetItemsParamPtrs{}
	}
	mmGetItems.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetItems.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetItems
}

// ExpectU1Param2 sets up expected param u1 for RestaurantService.GetItems
func (mmGetItems *mRestaurantServiceMockGetItems) ExpectU1Param2(u1 uuid.UUID) *mRestaurantServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &RestaurantServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.params != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Expect")
	}

	if mmGetItems.defaultExpectation.paramPtrs == nil {
		mmGetItems.defaultExpectation.paramPtrs = &RestaurantServiceMockGetItemsParamPtrs{}
	}
	mmGetItems.defaultExpectation.paramPtrs.u1 = &u1
	mmGetItems.defaultExpectation.expectationOrigins.originU1 = minimock.CallerInfo(1)

	return mmGetItems
}

// Inspect accepts an inspector function that has same arguments as the RestaurantService.GetItems
func (mmGetItems *mRestaurantServiceMockGetItems) Inspect(f func(ctx context.Context, u1 uuid.UUID)) *mRestaurantServiceMockGetItems {
	if mmGetItems.mock.inspectFuncGetItems != nil {
		mmGetItems.mock.t.Fatalf("Inspect function is already set for RestaurantServiceMock.GetItems")
	}

	mmGetItems.mock.inspectFuncGetItems = f

	return mmGetItems
}

// Return sets up results that will be returned by RestaurantService.GetItems
func (mmGetItems *mRestaurantServiceMockGetItems) Return(ma1 []domain.MenuItem, err error) *RestaurantServiceMock {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &RestaurantServiceMockGetItemsExpectation{mock: mmGetItems.mock}
	}
	mmGetItems.defaultExpectation.results = &RestaurantServiceMockGetItemsResults{ma1, err}
	mmGetItems.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// Set uses given function f to mock the RestaurantService.GetItems method
func (mmGetItems *mRestaurantServiceMockGetItems) Set(f func(ctx context.Context, u1 uuid.UUID) (ma1 []domain.MenuItem, err error)) *RestaurantServiceMock {
	if mmGetItems.defaultExpectation != nil {
		mmGetItems.mock.t.Fatalf("Default expectation is already set for the RestaurantService.GetItems method")
	}

	if len(mmGetItems.expectations) > 0 {
		mmGetItems.mock.t.Fatalf("Some expectations are already set for the RestaurantService.GetItems method")
	}

	mmGetItems.mock.funcGetItems = f
	mmGetItems.mock.funcGetItemsOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// When sets expectation for the RestaurantService.GetItems which will trigger the result defined by the following
// Then helper
func (mmGetItems *mRestaurantServiceMockGetItems) When(ctx context.Context, u1 uuid.UUID) *RestaurantServiceMockGetItemsExpectation {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("RestaurantServiceMock.GetItems mock is already set by Set")
	}

	expectation := &RestaurantServiceMockGetItemsExpectation{
		mock:               mmGetItems.mock,
		params:             &RestaurantServiceMockGetItemsParams{ctx, u1},
		expectationOrigins: RestaurantServiceMockGetItemsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetItems.expectations = append(mmGetItems.expectations, expectation)
	return expectation
}

// Then sets up RestaurantService.GetItems return parameters for the expectation previously defined by the When method
func (e *RestaurantServiceMockGetItemsExpectation) Then(ma1 []domain.MenuItem, err error) *RestaurantServiceMock {
	e.results = &RestaurantServiceMockGetItemsResults{ma1, err}
	return e.mock
}

// Times sets number of times RestaurantService.GetItems should be invoked
func (mmGetItems *mRestaurantServiceMockGetItems) Times(n uint64) *mRestaurantServiceMockGetItems {
	if n == 0 {
		mmGetItems.mock.t.Fatalf("Times of RestaurantServiceMock.GetItems mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetItems.expectedInvocations, n)
	mmGetItems.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetItems
}

func (mmGetItems *mRestaurantServiceMockGetItems) invocationsDone() bool {
	if len(mmGetItems.expectations) == 0 && mmGetItems.defaultExpectation == nil && mmGetItems.mock.funcGetItems == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetItems.mock.afterGetItemsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetItems.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetItems implements RestaurantService
func (mmGetItems *RestaurantServiceMock) GetItems(ctx context.Context, u1 uuid.UUID) (ma1 []domain.MenuItem, err error) {
	mm_atomic.AddUint64(&mmGetItems.beforeGetItemsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetItems.afterGetItemsCounter, 1)

	mmGetItems.t.Helper()

	if mmGetItems.inspectFuncGetItems != nil {
		mmGetItems.inspectFuncGetItems(ctx, u1)
	}

	mm_params := RestaurantServiceMockGetItemsParams{ctx, u1}

	// Record call args
	mmGetItems.GetItemsMock.mutex.Lock()
	mmGetItems.GetItemsMock.callArgs = append(mmGetItems.GetItemsMock.callArgs, &mm_params)
	mmGetItems.GetItemsMock.mutex.Unlock()

	for _, e := range mmGetItems.GetItemsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ma1, e.results.err
		}
	}

	if mmGetItems.GetItemsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetItems.GetItemsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetItems.GetItemsMock.defaultExpectation.params
		mm_want_ptrs := mmGetItems.GetItemsMock.defaultExpectation.paramPtrs

		mm_got := RestaurantServiceMockGetItemsParams{ctx, u1}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetItems.t.Errorf("RestaurantServiceMock.GetItems got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.u1 != nil && !minimock.Equal(*mm_want_ptrs.u1, mm_got.u1) {
				mmGetItems.t.Errorf("RestaurantServiceMock.GetItems got unexpected parameter u1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.originU1, *mm_want_ptrs.u1, mm_got.u1, minimock.Diff(*mm_want_ptrs.u1, mm_got.u1))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetItems.t.Errorf("RestaurantServiceMock.GetItems got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetItems.GetItemsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetItems.t.Fatal("No results are set for the RestaurantServiceMock.GetItems")
		}
		return (*mm_results).ma1, (*mm_results).err
	}
	if mmGetItems.funcGetItems != nil {
		return mmGetItems.funcGetItems(ctx, u1)
	}
	mmGetItems.t.Fatalf("Unexpected call to RestaurantServiceMock.GetItems. %v %v", ctx, u1)
	return
}

// GetItemsAfterCounter returns a count of finished RestaurantServiceMock.GetItems invocations
func (mmGetItems *RestaurantServiceMock) GetItemsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.afterGetItemsCounter)
}

// GetItemsBeforeCounter returns a count of RestaurantServiceMock.GetItems invocations
func (mmGetItems *RestaurantServiceMock) GetItemsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.beforeGetItemsCounter)
}

// Calls returns a list of arguments used in each call to RestaurantServiceMock.GetItems.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetItems *mRestaurantServiceMockGetItems) Calls() []*RestaurantServiceMockGetItemsParams {
	mmGetItems.mutex.RLock()

	argCopy := make([]*RestaurantServiceMockGetItemsParams, len(mmGetItems.callArgs))
	copy(argCopy, mmGetItems.callArgs)

	mmGetItems.mutex.RUnlock()

	return argCopy
}

// MinimockGetItemsDone returns true if the count of the GetItems invocations corresponds
// the number of defined expectations
func (m *RestaurantServiceMock) MinimockGetItemsDone() bool {
	if m.GetItemsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetItemsMock.invocationsDone()
}

// MinimockGetItemsInspect logs each unmet expectation
func (m *RestaurantServiceMock) MinimockGetItemsInspect() {
	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetItems at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetItemsCounter := mm_atomic.LoadUint64(&m.afterGetItemsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetItemsMock.defaultExpectation != nil && afterGetItemsCounter < 1 {
		if m.GetItemsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetItems at\n%s", m.GetItemsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetItems at\n%s with params: %#v", m.GetItemsMock.defaultExpectation.expectationOrigins.origin, *m.GetItemsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetItems != nil && afterGetItemsCounter < 1 {
		m.t.Errorf("Expected call to RestaurantServiceMock.GetItems at\n%s", m.funcGetItemsOrigin)
	}

	if !m.GetItemsMock.invocationsDone() && afterGetItemsCounter > 0 {
		m.t.Errorf("Expected %d calls to RestaurantServiceMock.GetItems at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetItemsMock.expectedInvocations), m.GetItemsMock.expectedInvocationsOrigin, afterGetItemsCounter)
	}
}

type mRestaurantServiceMockGetRestaurant struct {
	optional           bool
	mock               *RestaurantServiceMock
	defaultExpectation *RestaurantServiceMockGetRestaurantExpectation
	expectations       []*RestaurantServiceMockGetRestaurantExpectation

	callArgs []*RestaurantServiceMockGetRestaurantParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RestaurantServiceMockGetRestaurantExpectation specifies expectation struct of the RestaurantService.GetRestaurant
type RestaurantServiceMockGetRestaurantExpectation struct {
	mock               *RestaurantServiceMock
	params             *RestaurantServiceMockGetRestaurantParams
	paramPtrs          *RestaurantServiceMockGetRestaurantParamPtrs
	expectationOrigins RestaurantServiceMockGetRestaurantExpectationOrigins
	results            *RestaurantServiceMockGetRestaurantResults
	returnOrigin       string
	Counter            uint64
}

// RestaurantServiceMockGetRestaurantParams contains parameters of the RestaurantService.GetRestaurant
type RestaurantServiceMockGetRestaurantParams struct {
	ctx context.Context
	u1  uuid.UUID
}

// RestaurantServiceMockGetRestaurantParamPtrs contains pointers to parameters of the RestaurantService.GetRestaurant
type RestaurantServiceMockGetRestaurantParamPtrs struct {
	ctx *context.Context
	u1  *uuid.UUID
}

// RestaurantServiceMockGetRestaurantResults contains results of the RestaurantService.GetRestaurant
type RestaurantServiceMockGetRestaurantResults struct {
	r1  domain.Restaurant
	err error
}

// RestaurantServiceMockGetRestaurantOrigins contains origins of expectations of the RestaurantService.GetRestaurant
type RestaurantServiceMockGetRestaurantExpectationOrigins struct {
	origin    string
	originCtx string
	originU1  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Optional() *mRestaurantServiceMockGetRestaurant {
	mmGetRestaurant.optional = true
	return mmGetRestaurant
}

// Expect sets up expected params for RestaurantService.GetRestaurant
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Expect(ctx context.Context, u1 uuid.UUID) *mRestaurantServiceMockGetRestaurant {
	if mmGetRestaurant.mock.funcGetRestaurant != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Set")
	}

	if mmGetRestaurant.defaultExpectation == nil {
		mmGetRestaurant.defaultExpectation = &RestaurantServiceMockGetRestaurantExpectation{}
	}

	if mmGetRestaurant.defaultExpectation.paramPtrs != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by ExpectParams functions")
	}

	mmGetRestaurant.defaultExpectation.params = &RestaurantServiceMockGetRestaurantParams{ctx, u1}
	mmGetRestaurant.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetRestaurant.expectations {
		if minimock.Equal(e.params, mmGetRestaurant.defaultExpectation.params) {
			mmGetRestaurant.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRestaurant.defaultExpectation.params)
		}
	}

	return mmGetRestaurant
}

// ExpectCtxParam1 sets up expected param ctx for RestaurantService.GetRestaurant
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) ExpectCtxParam1(ctx context.Context) *mRestaurantServiceMockGetRestaurant {
	if mmGetRestaurant.mock.funcGetRestaurant != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Set")
	}

	if mmGetRestaurant.defaultExpectation == nil {
		mmGetRestaurant.defaultExpectation = &RestaurantServiceMockGetRestaurantExpectation{}
	}

	if mmGetRestaurant.defaultExpectation.params != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Expect")
	}

	if mmGetRestaurant.defaultExpectation.paramPtrs == nil {
		mmGetRestaurant.defaultExpectation.paramPtrs = &RestaurantServiceMockGetRestaurantParamPtrs{}
	}
	mmGetRestaurant.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetRestaurant.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetRestaurant
}

// ExpectU1Param2 sets up expected param u1 for RestaurantService.GetRestaurant
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) ExpectU1Param2(u1 uuid.UUID) *mRestaurantServiceMockGetRestaurant {
	if mmGetRestaurant.mock.funcGetRestaurant != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Set")
	}

	if mmGetRestaurant.defaultExpectation == nil {
		mmGetRestaurant.defaultExpectation = &RestaurantServiceMockGetRestaurantExpectation{}
	}

	if mmGetRestaurant.defaultExpectation.params != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Expect")
	}

	if mmGetRestaurant.defaultExpectation.paramPtrs == nil {
		mmGetRestaurant.defaultExpectation.paramPtrs = &RestaurantServiceMockGetRestaurantParamPtrs{}
	}
	mmGetRestaurant.defaultExpectation.paramPtrs.u1 = &u1
	mmGetRestaurant.defaultExpectation.expectationOrigins.originU1 = minimock.CallerInfo(1)

	return mmGetRestaurant
}

// Inspect accepts an inspector function that has same arguments as the RestaurantService.GetRestaurant
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Inspect(f func(ctx context.Context, u1 uuid.UUID)) *mRestaurantServiceMockGetRestaurant {
	if mmGetRestaurant.mock.inspectFuncGetRestaurant != nil {
		mmGetRestaurant.mock.t.Fatalf("Inspect function is already set for RestaurantServiceMock.GetRestaurant")
	}

	mmGetRestaurant.mock.inspectFuncGetRestaurant = f

	return mmGetRestaurant
}

// Return sets up results that will be returned by RestaurantService.GetRestaurant
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Return(r1 domain.Restaurant, err error) *RestaurantServiceMock {
	if mmGetRestaurant.mock.funcGetRestaurant != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Set")
	}

	if mmGetRestaurant.defaultExpectation == nil {
		mmGetRestaurant.defaultExpectation = &RestaurantServiceMockGetRestaurantExpectation{mock: mmGetRestaurant.mock}
	}
	mmGetRestaurant.defaultExpectation.results = &RestaurantServiceMockGetRestaurantResults{r1, err}
	mmGetRestaurant.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetRestaurant.mock
}

// Set uses given function f to mock the RestaurantService.GetRestaurant method
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Set(f func(ctx context.Context, u1 uuid.UUID) (r1 domain.Restaurant, err error)) *RestaurantServiceMock {
	if mmGetRestaurant.defaultExpectation != nil {
		mmGetRestaurant.mock.t.Fatalf("Default expectation is already set for the RestaurantService.GetRestaurant method")
	}

	if len(mmGetRestaurant.expectations) > 0 {
		mmGetRestaurant.mock.t.Fatalf("Some expectations are already set for the RestaurantService.GetRestaurant method")
	}

	mmGetRestaurant.mock.funcGetRestaurant = f
	mmGetRestaurant.mock.funcGetRestaurantOrigin = minimock.CallerInfo(1)
	return mmGetRestaurant.mock
}

// When sets expectation for the RestaurantService.GetRestaurant which will trigger the result defined by the following
// Then helper
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) When(ctx context.Context, u1 uuid.UUID) *RestaurantServiceMockGetRestaurantExpectation {
	if mmGetRestaurant.mock.funcGetRestaurant != nil {
		mmGetRestaurant.mock.t.Fatalf("RestaurantServiceMock.GetRestaurant mock is already set by Set")
	}

	expectation := &RestaurantServiceMockGetRestaurantExpectation{
		mock:               mmGetRestaurant.mock,
		params:             &RestaurantServiceMockGetRestaurantParams{ctx, u1},
		expectationOrigins: RestaurantServiceMockGetRestaurantExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetRestaurant.expectations = append(mmGetRestaurant.expectations, expectation)
	return expectation
}

// Then sets up RestaurantService.GetRestaurant return parameters for the expectation previously defined by the When method
func (e *RestaurantServiceMockGetRestaurantExpectation) Then(r1 domain.Restaurant, err error) *RestaurantServiceMock {
	e.results = &RestaurantServiceMockGetRestaurantResults{r1, err}
	return e.mock
}

// Times sets number of times RestaurantService.GetRestaurant should be invoked
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Times(n uint64) *mRestaurantServiceMockGetRestaurant {
	if n == 0 {
		mmGetRestaurant.mock.t.Fatalf("Times of RestaurantServiceMock.GetRestaurant mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetRestaurant.expectedInvocations, n)
	mmGetRestaurant.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetRestaurant
}

func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) invocationsDone() bool {
	if len(mmGetRestaurant.expectations) == 0 && mmGetRestaurant.defaultExpectation == nil && mmGetRestaurant.mock.funcGetRestaurant == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetRestaurant.mock.afterGetRestaurantCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetRestaurant.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetRestaurant implements RestaurantService
func (mmGetRestaurant *RestaurantServiceMock) GetRestaurant(ctx context.Context, u1 uuid.UUID) (r1 domain.Restaurant, err error) {
	mm_atomic.AddUint64(&mmGetRestaurant.beforeGetRestaurantCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRestaurant.afterGetRestaurantCounter, 1)

	mmGetRestaurant.t.Helper()

	if mmGetRestaurant.inspectFuncGetRestaurant != nil {
		mmGetRestaurant.inspectFuncGetRestaurant(ctx, u1)
	}

	mm_params := RestaurantServiceMockGetRestaurantParams{ctx, u1}

	// Record call args
	mmGetRestaurant.GetRestaurantMock.mutex.Lock()
	mmGetRestaurant.GetRestaurantMock.callArgs = append(mmGetRestaurant.GetRestaurantMock.callArgs, &mm_params)
	mmGetRestaurant.GetRestaurantMock.mutex.Unlock()

	for _, e := range mmGetRestaurant.GetRestaurantMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r1, e.results.err
		}
	}

	if mmGetRestaurant.GetRestaurantMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRestaurant.GetRestaurantMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRestaurant.GetRestaurantMock.defaultExpectation.params
		mm_want_ptrs := mmGetRestaurant.GetRestaurantMock.defaultExpectation.paramPtrs

		mm_got := RestaurantServiceMockGetRestaurantParams{ctx, u1}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetRestaurant.t.Errorf("RestaurantServiceMock.GetRestaurant got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRestaurant.GetRestaurantMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.u1 != nil && !minimock.Equal(*mm_want_ptrs.u1, mm_got.u1) {
				mmGetRestaurant.t.Errorf("RestaurantServiceMock.GetRestaurant got unexpected parameter u1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRestaurant.GetRestaurantMock.defaultExpectation.expectationOrigins.originU1, *mm_want_ptrs.u1, mm_got.u1, minimock.Diff(*mm_want_ptrs.u1, mm_got.u1))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRestaurant.t.Errorf("RestaurantServiceMock.GetRestaurant got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetRestaurant.GetRestaurantMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRestaurant.GetRestaurantMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRestaurant.t.Fatal("No results are set for the RestaurantServiceMock.GetRestaurant")
		}
		return (*mm_results).r1, (*mm_results).err
	}
	if mmGetRestaurant.funcGetRestaurant != nil {
		return mmGetRestaurant.funcGetRestaurant(ctx, u1)
	}
	mmGetRestaurant.t.Fatalf("Unexpected call to RestaurantServiceMock.GetRestaurant. %v %v", ctx, u1)
	return
}

// GetRestaurantAfterCounter returns a count of finished RestaurantServiceMock.GetRestaurant invocations
func (mmGetRestaurant *RestaurantServiceMock) GetRestaurantAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRestaurant.afterGetRestaurantCounter)
}

// GetRestaurantBeforeCounter returns a count of RestaurantServiceMock.GetRestaurant invocations
func (mmGetRestaurant *RestaurantServiceMock) GetRestaurantBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRestaurant.beforeGetRestaurantCounter)
}

// Calls returns a list of arguments used in each call to RestaurantServiceMock.GetRestaurant.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRestaurant *mRestaurantServiceMockGetRestaurant) Calls() []*RestaurantServiceMockGetRestaurantParams {
	mmGetRestaurant.mutex.RLock()

	argCopy := make([]*RestaurantServiceMockGetRestaurantParams, len(mmGetRestaurant.callArgs))
	copy(argCopy, mmGetRestaurant.callArgs)

	mmGetRestaurant.mutex.RUnlock()

	return argCopy
}

// MinimockGetRestaurantDone returns true if the count of the GetRestaurant invocations corresponds
// the number of defined expectations
func (m *RestaurantServiceMock) MinimockGetRestaurantDone() bool {
	if m.GetRestaurantMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetRestaurantMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetRestaurantMock.invocationsDone()
}

// MinimockGetRestaurantInspect logs each unmet expectation
func (m *RestaurantServiceMock) MinimockGetRestaurantInspect() {
	for _, e := range m.GetRestaurantMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurant at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetRestaurantCounter := mm_atomic.LoadUint64(&m.afterGetRestaurantCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetRestaurantMock.defaultExpectation != nil && afterGetRestaurantCounter < 1 {
		if m.GetRestaurantMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurant at\n%s", m.GetRestaurantMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurant at\n%s with params: %#v", m.GetRestaurantMock.defaultExpectation.expectationOrigins.origin, *m.GetRestaurantMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRestaurant != nil && afterGetRestaurantCounter < 1 {
		m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurant at\n%s", m.funcGetRestaurantOrigin)
	}

	if !m.GetRestaurantMock.invocationsDone() && afterGetRestaurantCounter > 0 {
		m.t.Errorf("Expected %d calls to RestaurantServiceMock.GetRestaurant at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetRestaurantMock.expectedInvocations), m.GetRestaurantMock.expectedInvocationsOrigin, afterGetRestaurantCounter)
	}
}

type mRestaurantServiceMockGetRestaurants struct {
	optional           bool
	mock               *RestaurantServiceMock
	defaultExpectation *RestaurantServiceMockGetRestaurantsExpectation
	expectations       []*RestaurantServiceMockGetRestaurantsExpectation

	callArgs []*RestaurantServiceMockGetRestaurantsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RestaurantServiceMockGetRestaurantsExpectation specifies expectation struct of the RestaurantService.GetRestaurants
type RestaurantServiceMockGetRestaurantsExpectation struct {
	mock               *RestaurantServiceMock
	params             *RestaurantServiceMockGetRestaurantsParams
	paramPtrs          *RestaurantServiceMockGetRestaurantsParamPtrs
	expectationOrigins RestaurantServiceMockGetRestaurantsExpectationOrigins
	results            *RestaurantServiceMockGetRestaurantsResults
	returnOrigin       string
	Counter            uint64
}

// RestaurantServiceMockGetRestaurantsParams contains parameters of the RestaurantService.GetRestaurants
type RestaurantServiceMockGetRestaurantsParams struct {
	ctx context.Context
}

// RestaurantServiceMockGetRestaurantsParamPtrs contains pointers to parameters of the RestaurantService.GetRestaurants
type RestaurantServiceMockGetRestaurantsParamPtrs struct {
	ctx *context.Context
}

// RestaurantServiceMockGetRestaurantsResults contains results of the RestaurantService.GetRestaurants
type RestaurantServiceMockGetRestaurantsResults struct {
	ra1 []domain.Restaurant
	err error
}

// RestaurantServiceMockGetRestaurantsOrigins contains origins of expectations of the RestaurantService.GetRestaurants
type RestaurantServiceMockGetRestaurantsExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Optional() *mRestaurantServiceMockGetRestaurants {
	mmGetRestaurants.optional = true
	return mmGetRestaurants
}

// Expect sets up expected params for RestaurantService.GetRestaurants
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Expect(ctx context.Context) *mRestaurantServiceMockGetRestaurants {
	if mmGetRestaurants.mock.funcGetRestaurants != nil {
		mmGetRestaurants.mock.t.Fatalf("RestaurantServiceMock.GetRestaurants mock is already set by Set")
	}

	if mmGetRestaurants.defaultExpectation == nil {
		mmGetRestaurants.defaultExpectation = &RestaurantServiceMockGetRestaurantsExpectation{}
	}

	if mmGetRestaurants.defaultExpectation.paramPtrs != nil {
		mmGetRestaurants.mock.t.Fatalf("RestaurantServiceMock.GetRestaurants mock is already set by ExpectParams functions")
	}

	mmGetRestaurants.defaultExpectation.params = &RestaurantServiceMockGetRestaurantsParams{ctx}
	mmGetRestaurants.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetRestaurants.expectations {
		if minimock.Equal(e.params, mmGetRestaurants.defaultExpectation.params) {
			mmGetRestaurants.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRestaurants.defaultExpectation.params)
		}
	}

	return mmGetRestaurants
}

// ExpectCtxParam1 sets up expected param ctx for RestaurantService.GetRestaurants
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) ExpectCtxParam1(ctx context.Context) *mRestaurantServiceMockGetRestaurants {
	if mmGetRestaurants.mock.funcGetRestaurants != nil {
		mmGetRestaurants.mock.t.Fatalf("RestaurantServiceMock.GetRestaurants mock is already set by Set")
	}

	if mmGetRestaurants.defaultExpectation == nil {
		mmGetRestaurants.defaultExpectation = &RestaurantServiceMockGetRestaurantsExpectation{}
	}

	if mmGetRestaurants.defaultExpectation.params != nil {
		mmGetRestaurants.mock.t.Fatalf("RestaurantServiceMock.GetRestaurants mock is already set by Expect")
	}

	if mmGetRestaurants.defaultExpectation.paramPtrs == nil {
		mmGetRestaurants.defaultExpectation.paramPtrs = &RestaurantServiceMockGetRestaurantsParamPtrs{}
	}
	mmGetRestaurants.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetRestaurants.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetRestaurants
}

// Inspect accepts an inspector function that has same arguments as the RestaurantService.GetRestaurants
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Inspect(f func(ctx context.Context)) *mRestaurantServiceMockGetRestaurants {
	if mmGetRestaurants.mock.inspectFuncGetRestaurants != nil {
		mmGetRestaurants.mock.t.Fatalf("Inspect function is already set for RestaurantServiceMock.GetRestaurants")
	}

	mmGetRestaurants.mock.inspectFuncGetRestaurants = f

	return mmGetRestaurants
}

// Return sets up results that will be returned by RestaurantService.GetRestaurants
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Return(ra1 []domain.Restaurant, err error) *RestaurantServiceMock {
	if mmGetRestaurants.mock.funcGetRestaurants != nil {
		mmGetRestaurants.mock.t.Fatalf("RestaurantServiceMock.GetRestaurants mock is already set by Set")
	}

	if mmGetRestaurants.defaultExpectation == nil {
		mmGetRestaurants.defaultExpectation = &RestaurantServiceMockGetRestaurantsExpectation{mock: mmGetRestaurants.mock}
	}
	mmGetRestaurants.defaultExpectation.results = &RestaurantServiceMockGetRestaurantsResults{ra1, err}
	mmGetRestaurants.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetRestaurants.mock
}

// Set uses given function f to mock the RestaurantService.GetRestaurants method
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Set(f func(ctx context.Context) (ra1 []domain.Restaurant, err error)) *RestaurantServiceMock {
	if mmGetRestaurants.defaultExpectation != nil {
		mmGetRestaurants.mock.t.Fatalf("Default expectation is already set for the RestaurantService.GetRestaurants method")
	}

	if len(mmGetRestaurants.expectations) > 0 {
		mmGetRestaurants.mock.t.Fatalf("Some expectations are already set for the RestaurantService.GetRestaurants method")
	}

	mmGetRestaurants.mock.funcGetRestaurants = f
	mmGetRestaurants.mock.funcGetRestaurantsOrigin = minimock.CallerInfo(1)
	return mmGetRestaurants.mock
}

// When sets expectation for the RestaurantService.GetRestaurants which will trigger the result defined by the following
// Then helper
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) When(ctx context.Context) *RestaurantServiceMockGetRestaurantsExpectation {
	if mmGetRestaurants.mock.funcGetRestaurants != nil {
		mmGetRestaurants.mock.t.Fatalf("RestaurantServiceMock.GetRestaurants mock is already set by Set")
	}

	expectation := &RestaurantServiceMockGetRestaurantsExpectation{
		mock:               mmGetRestaurants.mock,
		params:             &RestaurantServiceMockGetRestaurantsParams{ctx},
		expectationOrigins: RestaurantServiceMockGetRestaurantsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetRestaurants.expectations = append(mmGetRestaurants.expectations, expectation)
	return expectation
}

// Then sets up RestaurantService.GetRestaurants return parameters for the expectation previously defined by the When method
func (e *RestaurantServiceMockGetRestaurantsExpectation) Then(ra1 []domain.Restaurant, err error) *RestaurantServiceMock {
	e.results = &RestaurantServiceMockGetRestaurantsResults{ra1, err}
	return e.mock
}

// Times sets number of times RestaurantService.GetRestaurants should be invoked
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Times(n uint64) *mRestaurantServiceMockGetRestaurants {
	if n == 0 {
		mmGetRestaurants.mock.t.Fatalf("Times of RestaurantServiceMock.GetRestaurants mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetRestaurants.expectedInvocations, n)
	mmGetRestaurants.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetRestaurants
}

func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) invocationsDone() bool {
	if len(mmGetRestaurants.expectations) == 0 && mmGetRestaurants.defaultExpectation == nil && mmGetRestaurants.mock.funcGetRestaurants == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetRestaurants.mock.afterGetRestaurantsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetRestaurants.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetRestaurants implements RestaurantService
func (mmGetRestaurants *RestaurantServiceMock) GetRestaurants(ctx context.Context) (ra1 []domain.Restaurant, err error) {
	mm_atomic.AddUint64(&mmGetRestaurants.beforeGetRestaurantsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRestaurants.afterGetRestaurantsCounter, 1)

	mmGetRestaurants.t.Helper()

	if mmGetRestaurants.inspectFuncGetRestaurants != nil {
		mmGetRestaurants.inspectFuncGetRestaurants(ctx)
	}

	mm_params := RestaurantServiceMockGetRestaurantsParams{ctx}

	// Record call args
	mmGetRestaurants.GetRestaurantsMock.mutex.Lock()
	mmGetRestaurants.GetRestaurantsMock.callArgs = append(mmGetRestaurants.GetRestaurantsMock.callArgs, &mm_params)
	mmGetRestaurants.GetRestaurantsMock.mutex.Unlock()

	for _, e := range mmGetRestaurants.GetRestaurantsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ra1, e.results.err
		}
	}

	if mmGetRestaurants.GetRestaurantsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRestaurants.GetRestaurantsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRestaurants.GetRestaurantsMock.defaultExpectation.params
		mm_want_ptrs := mmGetRestaurants.GetRestaurantsMock.defaultExpectation.paramPtrs

		mm_got := RestaurantServiceMockGetRestaurantsParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetRestaurants.t.Errorf("RestaurantServiceMock.GetRestaurants got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRestaurants.GetRestaurantsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRestaurants.t.Errorf("RestaurantServiceMock.GetRestaurants got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetRestaurants.GetRestaurantsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRestaurants.GetRestaurantsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRestaurants.t.Fatal("No results are set for the RestaurantServiceMock.GetRestaurants")
		}
		return (*mm_results).ra1, (*mm_results).err
	}
	if mmGetRestaurants.funcGetRestaurants != nil {
		return mmGetRestaurants.funcGetRestaurants(ctx)
	}
	mmGetRestaurants.t.Fatalf("Unexpected call to RestaurantServiceMock.GetRestaurants. %v", ctx)
	return
}

// GetRestaurantsAfterCounter returns a count of finished RestaurantServiceMock.GetRestaurants invocations
func (mmGetRestaurants *RestaurantServiceMock) GetRestaurantsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRestaurants.afterGetRestaurantsCounter)
}

// GetRestaurantsBeforeCounter returns a count of RestaurantServiceMock.GetRestaurants invocations
func (mmGetRestaurants *RestaurantServiceMock) GetRestaurantsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRestaurants.beforeGetRestaurantsCounter)
}

// Calls returns a list of arguments used in each call to RestaurantServiceMock.GetRestaurants.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRestaurants *mRestaurantServiceMockGetRestaurants) Calls() []*RestaurantServiceMockGetRestaurantsParams {
	mmGetRestaurants.mutex.RLock()

	argCopy := make([]*RestaurantServiceMockGetRestaurantsParams, len(mmGetRestaurants.callArgs))
	copy(argCopy, mmGetRestaurants.callArgs)

	mmGetRestaurants.mutex.RUnlock()

	return argCopy
}

// MinimockGetRestaurantsDone returns true if the count of the GetRestaurants invocations corresponds
// the number of defined expectations
func (m *RestaurantServiceMock) MinimockGetRestaurantsDone() bool {
	if m.GetRestaurantsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetRestaurantsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetRestaurantsMock.invocationsDone()
}

// MinimockGetRestaurantsInspect logs each unmet expectation
func (m *RestaurantServiceMock) MinimockGetRestaurantsInspect() {
	for _, e := range m.GetRestaurantsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurants at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetRestaurantsCounter := mm_atomic.LoadUint64(&m.afterGetRestaurantsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetRestaurantsMock.defaultExpectation != nil && afterGetRestaurantsCounter < 1 {
		if m.GetRestaurantsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurants at\n%s", m.GetRestaurantsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurants at\n%s with params: %#v", m.GetRestaurantsMock.defaultExpectation.expectationOrigins.origin, *m.GetRestaurantsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRestaurants != nil && afterGetRestaurantsCounter < 1 {
		m.t.Errorf("Expected call to RestaurantServiceMock.GetRestaurants at\n%s", m.funcGetRestaurantsOrigin)
	}

	if !m.GetRestaurantsMock.invocationsDone() && afterGetRestaurantsCounter > 0 {
		m.t.Errorf("Expected %d calls to RestaurantServiceMock.GetRestaurants at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetRestaurantsMock.expectedInvocations), m.GetRestaurantsMock.expectedInvocationsOrigin, afterGetRestaurantsCounter)
	}
}

type mRestaurantServiceMockPutMenuItem struct {
	optional           bool
	mock               *RestaurantServiceMock
	defaultExpectation *RestaurantServiceMockPutMenuItemExpectation
	expectations       []*RestaurantServiceMockPutMenuItemExpectation

	callArgs []*RestaurantServiceMockPutMenuItemParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RestaurantServiceMockPutMenuItemExpectation specifies expectation struct of the RestaurantService.PutMenuItem
type RestaurantServiceMockPutMenuItemExpectation struct {
	mock               *RestaurantServiceMock
	params             *RestaurantServiceMockPutMenuItemParams
	paramPtrs          *RestaurantServiceMockPutMenuItemParamPtrs
	expectationOrigins RestaurantServiceMockPutMenuItemExpectationOrigins
	results            *RestaurantServiceMockPutMenuItemResults
	returnOrigin       string
	Counter            uint64
}

// RestaurantServiceMockPutMenuItemParams contains parameters of the RestaurantService.PutMenuItem
type RestaurantServiceMockPutMenuItemParams struct {
	ctx context.Context
	u1  uuid.UUID
	m1  domain.MenuItem
}

// RestaurantServiceMockPutMenuItemParamPtrs contains pointers to parameters of the RestaurantService.PutMenuItem
type RestaurantServiceMockPutMenuItemParamPtrs struct {
	ctx *context.Context
	u1  *uuid.UUID
	m1  *domain.MenuItem
}

// RestaurantServiceMockPutMenuItemResults contains results of the RestaurantService.PutMenuItem
type RestaurantServiceMockPutMenuItemResults struct {
	m2  domain.MenuItem
	err error
}

// RestaurantServiceMockPutMenuItemOrigins contains origins of expectations of the RestaurantService.PutMenuItem
type RestaurantServiceMockPutMenuItemExpectationOrigins struct {
	origin    string
	originCtx string
	originU1  string
	originM1  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Optional() *mRestaurantServiceMockPutMenuItem {
	mmPutMenuItem.optional = true
	return mmPutMenuItem
}

// Expect sets up expected params for RestaurantService.PutMenuItem
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Expect(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem) *mRestaurantServiceMockPutMenuItem {
	if mmPutMenuItem.mock.funcPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Set")
	}

	if mmPutMenuItem.defaultExpectation == nil {
		mmPutMenuItem.defaultExpectation = &RestaurantServiceMockPutMenuItemExpectation{}
	}

	if mmPutMenuItem.defaultExpectation.paramPtrs != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by ExpectParams functions")
	}

	mmPutMenuItem.defaultExpectation.params = &RestaurantServiceMockPutMenuItemParams{ctx, u1, m1}
	mmPutMenuItem.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPutMenuItem.expectations {
		if minimock.Equal(e.params, mmPutMenuItem.defaultExpectation.params) {
			mmPutMenuItem.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPutMenuItem.defaultExpectation.params)
		}
	}

	return mmPutMenuItem
}

// ExpectCtxParam1 sets up expected param ctx for RestaurantService.PutMenuItem
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) ExpectCtxParam1(ctx context.Context) *mRestaurantServiceMockPutMenuItem {
	if mmPutMenuItem.mock.funcPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Set")
	}

	if mmPutMenuItem.defaultExpectation == nil {
		mmPutMenuItem.defaultExpectation = &RestaurantServiceMockPutMenuItemExpectation{}
	}

	if mmPutMenuItem.defaultExpectation.params != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Expect")
	}

	if mmPutMenuItem.defaultExpectation.paramPtrs == nil {
		mmPutMenuItem.defaultExpectation.paramPtrs = &RestaurantServiceMockPutMenuItemParamPtrs{}
	}
	mmPutMenuItem.defaultExpectation.paramPtrs.ctx = &ctx
	mmPutMenuItem.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPutMenuItem
}

// ExpectU1Param2 sets up expected param u1 for RestaurantService.PutMenuItem
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) ExpectU1Param2(u1 uuid.UUID) *mRestaurantServiceMockPutMenuItem {
	if mmPutMenuItem.mock.funcPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Set")
	}

	if mmPutMenuItem.defaultExpectation == nil {
		mmPutMenuItem.defaultExpectation = &RestaurantServiceMockPutMenuItemExpectation{}
	}

	if mmPutMenuItem.defaultExpectation.params != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Expect")
	}

	if mmPutMenuItem.defaultExpectation.paramPtrs == nil {
		mmPutMenuItem.defaultExpectation.paramPtrs = &RestaurantServiceMockPutMenuItemParamPtrs{}
	}
	mmPutMenuItem.defaultExpectation.paramPtrs.u1 = &u1
	mmPutMenuItem.defaultExpectation.expectationOrigins.originU1 = minimock.CallerInfo(1)

	return mmPutMenuItem
}

// ExpectM1Param3 sets up expected param m1 for RestaurantService.PutMenuItem
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) ExpectM1Param3(m1 domain.MenuItem) *mRestaurantServiceMockPutMenuItem {
	if mmPutMenuItem.mock.funcPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Set")
	}

	if mmPutMenuItem.defaultExpectation == nil {
		mmPutMenuItem.defaultExpectation = &RestaurantServiceMockPutMenuItemExpectation{}
	}

	if mmPutMenuItem.defaultExpectation.params != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Expect")
	}

	if mmPutMenuItem.defaultExpectation.paramPtrs == nil {
		mmPutMenuItem.defaultExpectation.paramPtrs = &RestaurantServiceMockPutMenuItemParamPtrs{}
	}
	mmPutMenuItem.defaultExpectation.paramPtrs.m1 = &m1
	mmPutMenuItem.defaultExpectation.expectationOrigins.originM1 = minimock.CallerInfo(1)

	return mmPutMenuItem
}

// Inspect accepts an inspector function that has same arguments as the RestaurantService.PutMenuItem
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Inspect(f func(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem)) *mRestaurantServiceMockPutMenuItem {
	if mmPutMenuItem.mock.inspectFuncPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("Inspect function is already set for RestaurantServiceMock.PutMenuItem")
	}

	mmPutMenuItem.mock.inspectFuncPutMenuItem = f

	return mmPutMenuItem
}

// Return sets up results that will be returned by RestaurantService.PutMenuItem
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Return(m2 domain.MenuItem, err error) *RestaurantServiceMock {
	if mmPutMenuItem.mock.funcPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Set")
	}

	if mmPutMenuItem.defaultExpectation == nil {
		mmPutMenuItem.defaultExpectation = &RestaurantServiceMockPutMenuItemExpectation{mock: mmPutMenuItem.mock}
	}
	mmPutMenuItem.defaultExpectation.results = &RestaurantServiceMockPutMenuItemResults{m2, err}
	mmPutMenuItem.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPutMenuItem.mock
}

// Set uses given function f to mock the RestaurantService.PutMenuItem method
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Set(f func(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem) (m2 domain.MenuItem, err error)) *RestaurantServiceMock {
	if mmPutMenuItem.defaultExpectation != nil {
		mmPutMenuItem.mock.t.Fatalf("Default expectation is already set for the RestaurantService.PutMenuItem method")
	}

	if len(mmPutMenuItem.expectations) > 0 {
		mmPutMenuItem.mock.t.Fatalf("Some expectations are already set for the RestaurantService.PutMenuItem method")
	}

	mmPutMenuItem.mock.funcPutMenuItem = f
	mmPutMenuItem.mock.funcPutMenuItemOrigin = minimock.CallerInfo(1)
	return mmPutMenuItem.mock
}

// When sets expectation for the RestaurantService.PutMenuItem which will trigger the result defined by the following
// Then helper
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) When(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem) *RestaurantServiceMockPutMenuItemExpectation {
	if mmPutMenuItem.mock.funcPutMenuItem != nil {
		mmPutMenuItem.mock.t.Fatalf("RestaurantServiceMock.PutMenuItem mock is already set by Set")
	}

	expectation := &RestaurantServiceMockPutMenuItemExpectation{
		mock:               mmPutMenuItem.mock,
		params:             &RestaurantServiceMockPutMenuItemParams{ctx, u1, m1},
		expectationOrigins: RestaurantServiceMockPutMenuItemExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPutMenuItem.expectations = append(mmPutMenuItem.expectations, expectation)
	return expectation
}

// Then sets up RestaurantService.PutMenuItem return parameters for the expectation previously defined by the When method
func (e *RestaurantServiceMockPutMenuItemExpectation) Then(m2 domain.MenuItem, err error) *RestaurantServiceMock {
	e.results = &RestaurantServiceMockPutMenuItemResults{m2, err}
	return e.mock
}

// Times sets number of times RestaurantService.PutMenuItem should be invoked
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Times(n uint64) *mRestaurantServiceMockPutMenuItem {
	if n == 0 {
		mmPutMenuItem.mock.t.Fatalf("Times of RestaurantServiceMock.PutMenuItem mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPutMenuItem.expectedInvocations, n)
	mmPutMenuItem.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPutMenuItem
}

func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) invocationsDone() bool {
	if len(mmPutMenuItem.expectations) == 0 && mmPutMenuItem.defaultExpectation == nil && mmPutMenuItem.mock.funcPutMenuItem == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPutMenuItem.mock.afterPutMenuItemCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPutMenuItem.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PutMenuItem implements RestaurantService
func (mmPutMenuItem *RestaurantServiceMock) PutMenuItem(ctx context.Context, u1 uuid.UUID, m1 domain.MenuItem) (m2 domain.MenuItem, err error) {
	mm_atomic.AddUint64(&mmPutMenuItem.beforePutMenuItemCounter, 1)
	defer mm_atomic.AddUint64(&mmPutMenuItem.afterPutMenuItemCounter, 1)

	mmPutMenuItem.t.Helper()

	if mmPutMenuItem.inspectFuncPutMenuItem != nil {
		mmPutMenuItem.inspectFuncPutMenuItem(ctx, u1, m1)
	}

	mm_params := RestaurantServiceMockPutMenuItemParams{ctx, u1, m1}

	// Record call args
	mmPutMenuItem.PutMenuItemMock.mutex.Lock()
	mmPutMenuItem.PutMenuItemMock.callArgs = append(mmPutMenuItem.PutMenuItemMock.callArgs, &mm_params)
	mmPutMenuItem.PutMenuItemMock.mutex.Unlock()

	for _, e := range mmPutMenuItem.PutMenuItemMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.m2, e.results.err
		}
	}

	if mmPutMenuItem.PutMenuItemMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPutMenuItem.PutMenuItemMock.defaultExpectation.Counter, 1)
		mm_want := mmPutMenuItem.PutMenuItemMock.defaultExpectation.params
		mm_want_ptrs := mmPutMenuItem.PutMenuItemMock.defaultExpectation.paramPtrs

		mm_got := RestaurantServiceMockPutMenuItemParams{ctx, u1, m1}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPutMenuItem.t.Errorf("RestaurantServiceMock.PutMenuItem got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutMenuItem.PutMenuItemMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.u1 != nil && !minimock.Equal(*mm_want_ptrs.u1, mm_got.u1) {
				mmPutMenuItem.t.Errorf("RestaurantServiceMock.PutMenuItem got unexpected parameter u1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutMenuItem.PutMenuItemMock.defaultExpectation.expectationOrigins.originU1, *mm_want_ptrs.u1, mm_got.u1, minimock.Diff(*mm_want_ptrs.u1, mm_got.u1))
			}

			if mm_want_ptrs.m1 != nil && !minimock.Equal(*mm_want_ptrs.m1, mm_got.m1) {
				mmPutMenuItem.t.Errorf("RestaurantServiceMock.PutMenuItem got unexpected parameter m1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutMenuItem.PutMenuItemMock.defaultExpectation.expectationOrigins.originM1, *mm_want_ptrs.m1, mm_got.m1, minimock.Diff(*mm_want_ptrs.m1, mm_got.m1))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPutMenuItem.t.Errorf("RestaurantServiceMock.PutMenuItem got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPutMenuItem.PutMenuItemMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPutMenuItem.PutMenuItemMock.defaultExpectation.results
		if mm_results == nil {
			mmPutMenuItem.t.Fatal("No results are set for the RestaurantServiceMock.PutMenuItem")
		}
		return (*mm_results).m2, (*mm_results).err
	}
	if mmPutMenuItem.funcPutMenuItem != nil {
		return mmPutMenuItem.funcPutMenuItem(ctx, u1, m1)
	}
	mmPutMenuItem.t.Fatalf("Unexpected call to RestaurantServiceMock.PutMenuItem. %v %v %v", ctx, u1, m1)
	return
}

// PutMenuItemAfterCounter returns a count of finished RestaurantServiceMock.PutMenuItem invocations
func (mmPutMenuItem *RestaurantServiceMock) PutMenuItemAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutMenuItem.afterPutMenuItemCounter)
}

// PutMenuItemBeforeCounter returns a count of RestaurantServiceMock.PutMenuItem invocations
func (mmPutMenuItem *RestaurantServiceMock) PutMenuItemBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutMenuItem.beforePutMenuItemCounter)
}

// Calls returns a list of arguments used in each call to RestaurantServiceMock.PutMenuItem.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPutMenuItem *mRestaurantServiceMockPutMenuItem) Calls() []*RestaurantServiceMockPutMenuItemParams {
	mmPutMenuItem.mutex.RLock()

	argCopy := make([]*RestaurantServiceMockPutMenuItemParams, len(mmPutMenuItem.callArgs))
	copy(argCopy, mmPutMenuItem.callArgs)

	mmPutMenuItem.mutex.RUnlock()

	return argCopy
}

// MinimockPutMenuItemDone returns true if the count of the PutMenuItem invocations corresponds
// the number of defined expectations
func (m *RestaurantServiceMock) MinimockPutMenuItemDone() bool {
	if m.PutMenuItemMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PutMenuItemMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PutMenuItemMock.invocationsDone()
}

// MinimockPutMenuItemInspect logs each unmet expectation
func (m *RestaurantServiceMock) MinimockPutMenuItemInspect() {
	for _, e := range m.PutMenuItemMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RestaurantServiceMock.PutMenuItem at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPutMenuItemCounter := mm_atomic.LoadUint64(&m.afterPutMenuItemCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PutMenuItemMock.defaultExpectation != nil && afterPutMenuItemCounter < 1 {
		if m.PutMenuItemMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RestaurantServiceMock.PutMenuItem at\n%s", m.PutMenuItemMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RestaurantServiceMock.PutMenuItem at\n%s with params: %#v", m.PutMenuItemMock.defaultExpectation.expectationOrigins.origin, *m.PutMenuItemMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPutMenuItem != nil && afterPutMenuItemCounter < 1 {
		m.t.Errorf("Expected call to RestaurantServiceMock.PutMenuItem at\n%s", m.funcPutMenuItemOrigin)
	}

	if !m.PutMenuItemMock.invocationsDone() && afterPutMenuItemCounter > 0 {
		m.t.Errorf("Expected %d calls to RestaurantServiceMock.PutMenuItem at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PutMenuItemMock.expectedInvocations), m.PutMenuItemMock.expectedInvocationsOrigin, afterPutMenuItemCounter)
	}
}

type mRestaurantServiceMockPutRestaurant struct {
	optional           bool
	mock               *RestaurantServiceMock
	defaultExpectation *RestaurantServiceMockPutRestaurantExpectation
	expectations       []*RestaurantServiceMockPutRestaurantExpectation

	callArgs []*RestaurantServiceMockPutRestaurantParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RestaurantServiceMockPutRestaurantExpectation specifies expectation struct of the RestaurantService.PutRestaurant
type RestaurantServiceMockPutRestaurantExpectation struct {
	mock               *RestaurantServiceMock
	params             *RestaurantServiceMockPutRestaurantParams
	paramPtrs          *RestaurantServiceMockPutRestaurantParamPtrs
	expectationOrigins RestaurantServiceMockPutRestaurantExpectationOrigins
	results            *RestaurantServiceMockPutRestaurantResults
	returnOrigin       string
	Counter            uint64
}

// RestaurantServiceMockPutRestaurantParams contains parameters of the RestaurantService.PutRestaurant
type RestaurantServiceMockPutRestaurantParams struct {
	ctx context.Context
	r1  domain.Restaurant
}

// RestaurantServiceMockPutRestaurantParamPtrs contains pointers to parameters of the RestaurantService.PutRestaurant
type RestaurantServiceMockPutRestaurantParamPtrs struct {
	ctx *context.Context
	r1  *domain.Restaurant
}

// RestaurantServiceMockPutRestaurantResults contains results of the RestaurantService.PutRestaurant
type RestaurantServiceMockPutRestaurantResults struct {
	r2  domain.Restaurant
	err error
}

// RestaurantServiceMockPutRestaurantOrigins contains origins of expectations of the RestaurantService.PutRestaurant
type RestaurantServiceMockPutRestaurantExpectationOrigins struct {
	origin    string
	originCtx string
	originR1  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Optional() *mRestaurantServiceMockPutRestaurant {
	mmPutRestaurant.optional = true
	return mmPutRestaurant
}

// Expect sets up expected params for RestaurantService.PutRestaurant
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Expect(ctx context.Context, r1 domain.Restaurant) *mRestaurantServiceMockPutRestaurant {
	if mmPutRestaurant.mock.funcPutRestaurant != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Set")
	}

	if mmPutRestaurant.defaultExpectation == nil {
		mmPutRestaurant.defaultExpectation = &RestaurantServiceMockPutRestaurantExpectation{}
	}

	if mmPutRestaurant.defaultExpectation.paramPtrs != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by ExpectParams functions")
	}

	mmPutRestaurant.defaultExpectation.params = &RestaurantServiceMockPutRestaurantParams{ctx, r1}
	mmPutRestaurant.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPutRestaurant.expectations {
		if minimock.Equal(e.params, mmPutRestaurant.defaultExpectation.params) {
			mmPutRestaurant.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPutRestaurant.defaultExpectation.params)
		}
	}

	return mmPutRestaurant
}

// ExpectCtxParam1 sets up expected param ctx for RestaurantService.PutRestaurant
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) ExpectCtxParam1(ctx context.Context) *mRestaurantServiceMockPutRestaurant {
	if mmPutRestaurant.mock.funcPutRestaurant != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Set")
	}

	if mmPutRestaurant.defaultExpectation == nil {
		mmPutRestaurant.defaultExpectation = &RestaurantServiceMockPutRestaurantExpectation{}
	}

	if mmPutRestaurant.defaultExpectation.params != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Expect")
	}

	if mmPutRestaurant.defaultExpectation.paramPtrs == nil {
		mmPutRestaurant.defaultExpectation.paramPtrs = &RestaurantServiceMockPutRestaurantParamPtrs{}
	}
	mmPutRestaurant.defaultExpectation.paramPtrs.ctx = &ctx
	mmPutRestaurant.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPutRestaurant
}

// ExpectR1Param2 sets up expected param r1 for RestaurantService.PutRestaurant
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) ExpectR1Param2(r1 domain.Restaurant) *mRestaurantServiceMockPutRestaurant {
	if mmPutRestaurant.mock.funcPutRestaurant != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Set")
	}

	if mmPutRestaurant.defaultExpectation == nil {
		mmPutRestaurant.defaultExpectation = &RestaurantServiceMockPutRestaurantExpectation{}
	}

	if mmPutRestaurant.defaultExpectation.params != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Expect")
	}

	if mmPutRestaurant.defaultExpectation.paramPtrs == nil {
		mmPutRestaurant.defaultExpectation.paramPtrs = &RestaurantServiceMockPutRestaurantParamPtrs{}
	}
	mmPutRestaurant.defaultExpectation.paramPtrs.r1 = &r1
	mmPutRestaurant.defaultExpectation.expectationOrigins.originR1 = minimock.CallerInfo(1)

	return mmPutRestaurant
}

// Inspect accepts an inspector function that has same arguments as the RestaurantService.PutRestaurant
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Inspect(f func(ctx context.Context, r1 domain.Restaurant)) *mRestaurantServiceMockPutRestaurant {
	if mmPutRestaurant.mock.inspectFuncPutRestaurant != nil {
		mmPutRestaurant.mock.t.Fatalf("Inspect function is already set for RestaurantServiceMock.PutRestaurant")
	}

	mmPutRestaurant.mock.inspectFuncPutRestaurant = f

	return mmPutRestaurant
}

// Return sets up results that will be returned by RestaurantService.PutRestaurant
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Return(r2 domain.Restaurant, err error) *RestaurantServiceMock {
	if mmPutRestaurant.mock.funcPutRestaurant != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Set")
	}

	if mmPutRestaurant.defaultExpectation == nil {
		mmPutRestaurant.defaultExpectation = &RestaurantServiceMockPutRestaurantExpectation{mock: mmPutRestaurant.mock}
	}
	mmPutRestaurant.defaultExpectation.results = &RestaurantServiceMockPutRestaurantResults{r2, err}
	mmPutRestaurant.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPutRestaurant.mock
}

// Set uses given function f to mock the RestaurantService.PutRestaurant method
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Set(f func(ctx context.Context, r1 domain.Restaurant) (r2 domain.Restaurant, err error)) *RestaurantServiceMock {
	if mmPutRestaurant.defaultExpectation != nil {
		mmPutRestaurant.mock.t.Fatalf("Default expectation is already set for the RestaurantService.PutRestaurant method")
	}

	if len(mmPutRestaurant.expectations) > 0 {
		mmPutRestaurant.mock.t.Fatalf("Some expectations are already set for the RestaurantService.PutRestaurant method")
	}

	mmPutRestaurant.mock.funcPutRestaurant = f
	mmPutRestaurant.mock.funcPutRestaurantOrigin = minimock.CallerInfo(1)
	return mmPutRestaurant.mock
}

// When sets expectation for the RestaurantService.PutRestaurant which will trigger the result defined by the following
// Then helper
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) When(ctx context.Context, r1 domain.Restaurant) *RestaurantServiceMockPutRestaurantExpectation {
	if mmPutRestaurant.mock.funcPutRestaurant != nil {
		mmPutRestaurant.mock.t.Fatalf("RestaurantServiceMock.PutRestaurant mock is already set by Set")
	}

	expectation := &RestaurantServiceMockPutRestaurantExpectation{
		mock:               mmPutRestaurant.mock,
		params:             &RestaurantServiceMockPutRestaurantParams{ctx, r1},
		expectationOrigins: RestaurantServiceMockPutRestaurantExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPutRestaurant.expectations = append(mmPutRestaurant.expectations, expectation)
	return expectation
}

// Then sets up RestaurantService.PutRestaurant return parameters for the expectation previously defined by the When method
func (e *RestaurantServiceMockPutRestaurantExpectation) Then(r2 domain.Restaurant, err error) *RestaurantServiceMock {
	e.results = &RestaurantServiceMockPutRestaurantResults{r2, err}
	return e.mock
}

// Times sets number of times RestaurantService.PutRestaurant should be invoked
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Times(n uint64) *mRestaurantServiceMockPutRestaurant {
	if n == 0 {
		mmPutRestaurant.mock.t.Fatalf("Times of RestaurantServiceMock.PutRestaurant mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPutRestaurant.expectedInvocations, n)
	mmPutRestaurant.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPutRestaurant
}

func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) invocationsDone() bool {
	if len(mmPutRestaurant.expectations) == 0 && mmPutRestaurant.defaultExpectation == nil && mmPutRestaurant.mock.funcPutRestaurant == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPutRestaurant.mock.afterPutRestaurantCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPutRestaurant.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PutRestaurant implements RestaurantService
func (mmPutRestaurant *RestaurantServiceMock) PutRestaurant(ctx context.Context, r1 domain.Restaurant) (r2 domain.Restaurant, err error) {
	mm_atomic.AddUint64(&mmPutRestaurant.beforePutRestaurantCounter, 1)
	defer mm_atomic.AddUint64(&mmPutRestaurant.afterPutRestaurantCounter, 1)

	mmPutRestaurant.t.Helper()

	if mmPutRestaurant.inspectFuncPutRestaurant != nil {
		mmPutRestaurant.inspectFuncPutRestaurant(ctx, r1)
	}

	mm_params := RestaurantServiceMockPutRestaurantParams{ctx, r1}

	// Record call args
	mmPutRestaurant.PutRestaurantMock.mutex.Lock()
	mmPutRestaurant.PutRestaurantMock.callArgs = append(mmPutRestaurant.PutRestaurantMock.callArgs, &mm_params)
	mmPutRestaurant.PutRestaurantMock.mutex.Unlock()

	for _, e := range mmPutRestaurant.PutRestaurantMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.r2, e.results.err
		}
	}

	if mmPutRestaurant.PutRestaurantMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPutRestaurant.PutRestaurantMock.defaultExpectation.Counter, 1)
		mm_want := mmPutRestaurant.PutRestaurantMock.defaultExpectation.params
		mm_want_ptrs := mmPutRestaurant.PutRestaurantMock.defaultExpectation.paramPtrs

		mm_got := RestaurantServiceMockPutRestaurantParams{ctx, r1}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPutRestaurant.t.Errorf("RestaurantServiceMock.PutRestaurant got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutRestaurant.PutRestaurantMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.r1 != nil && !minimock.Equal(*mm_want_ptrs.r1, mm_got.r1) {
				mmPutRestaurant.t.Errorf("RestaurantServiceMock.PutRestaurant got unexpected parameter r1, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPutRestaurant.PutRestaurantMock.defaultExpectation.expectationOrigins.originR1, *mm_want_ptrs.r1, mm_got.r1, minimock.Diff(*mm_want_ptrs.r1, mm_got.r1))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPutRestaurant.t.Errorf("RestaurantServiceMock.PutRestaurant got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPutRestaurant.PutRestaurantMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPutRestaurant.PutRestaurantMock.defaultExpectation.results
		if mm_results == nil {
			mmPutRestaurant.t.Fatal("No results are set for the RestaurantServiceMock.PutRestaurant")
		}
		return (*mm_results).r2, (*mm_results).err
	}
	if mmPutRestaurant.funcPutRestaurant != nil {
		return mmPutRestaurant.funcPutRestaurant(ctx, r1)
	}
	mmPutRestaurant.t.Fatalf("Unexpected call to RestaurantServiceMock.PutRestaurant. %v %v", ctx, r1)
	return
}

// PutRestaurantAfterCounter returns a count of finished RestaurantServiceMock.PutRestaurant invocations
func (mmPutRestaurant *RestaurantServiceMock) PutRestaurantAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutRestaurant.afterPutRestaurantCounter)
}

// PutRestaurantBeforeCounter returns a count of RestaurantServiceMock.PutRestaurant invocations
func (mmPutRestaurant *RestaurantServiceMock) PutRestaurantBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPutRestaurant.beforePutRestaurantCounter)
}

// Calls returns a list of arguments used in each call to RestaurantServiceMock.PutRestaurant.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPutRestaurant *mRestaurantServiceMockPutRestaurant) Calls() []*RestaurantServiceMockPutRestaurantParams {
	mmPutRestaurant.mutex.RLock()

	argCopy := make([]*RestaurantServiceMockPutRestaurantParams, len(mmPutRestaurant.callArgs))
	copy(argCopy, mmPutRestaurant.callArgs)

	mmPutRestaurant.mutex.RUnlock()

	return argCopy
}

// MinimockPutRestaurantDone returns true if the count of the PutRestaurant invocations corresponds
// the number of defined expectations
func (m *RestaurantServiceMock) MinimockPutRestaurantDone() bool {
	if m.PutRestaurantMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PutRestaurantMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PutRestaurantMock.invocationsDone()
}

// MinimockPutRestaurantInspect logs each unmet expectation
func (m *RestaurantServiceMock) MinimockPutRestaurantInspect() {
	for _, e := range m.PutRestaurantMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RestaurantServiceMock.PutRestaurant at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPutRestaurantCounter := mm_atomic.LoadUint64(&m.afterPutRestaurantCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PutRestaurantMock.defaultExpectation != nil && afterPutRestaurantCounter < 1 {
		if m.PutRestaurantMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RestaurantServiceMock.PutRestaurant at\n%s", m.PutRestaurantMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RestaurantServiceMock.PutRestaurant at\n%s with params: %#v", m.PutRestaurantMock.defaultExpectation.expectationOrigins.origin, *m.PutRestaurantMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPutRestaurant != nil && afterPutRestaurantCounter < 1 {
		m.t.Errorf("Expected call to RestaurantServiceMock.PutRestaurant at\n%s", m.funcPutRestaurantOrigin)
	}

	if !m.PutRestaurantMock.invocationsDone() && afterPutRestaurantCounter > 0 {
		m.t.Errorf("Expected %d calls to RestaurantServiceMock.PutRestaurant at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PutRestaurantMock.expectedInvocations), m.PutRestaurantMock.expectedInvocationsOrigin, afterPutRestaurantCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RestaurantServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetItemInspect()

			m.MinimockGetItemsInspect()

			m.MinimockGetRestaurantInspect()

			m.MinimockGetRestaurantsInspect()

			m.MinimockPutMenuItemInspect()

			m.MinimockPutRestaurantInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RestaurantServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RestaurantServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetItemDone() &&
		m.MinimockGetItemsDone() &&
		m.MinimockGetRestaurantDone() &&
		m.MinimockGetRestaurantsDone() &&
		m.MinimockPutMenuItemDone() &&
		m.MinimockPutRestaurantDone()
}
